# fly.toml app configuration file generated for review-guru-server on 2024-07-15T21:14:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'review-guru-server'
primary_region = 'ams'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
